[build]
	# A list of Git repositories to include as dependencies.
	# Format: "remote:username/repo@branch"
	# Example: ["github.com:worseuserr/RojoSDK@main"]
	Dependencies = []

	# How often to check for dependency updates.
	# Options: "never", "daily", "on_build"
	DependencyCheckFrequency = "daily"

	# If true, automatically pulls dependency changes when a new commit is found.
	AutoUpdateDependencies = false

	# If true, prints a notification during the build if any dependencies are outdated.
	# This option is overriden by AutoUpdateDependencies.
	NotifyOutdatedDependencies = true

	# If true, removes dependency Git entries if the
	# dependency is removed from Dependencies (does not remove from lib/)
	AutoClearDependencies = true

	# A list of alternate source directories to look for if a dependency
	# does not have 'build.py' or a 'src' folder.
	DependencySources = []

	# A list of options to automatically supply to build.py when it is ran.
	# Example: ["-v", "--no-cleanup"]
	BuildOptions = []

	# Sets the default logging verbosity. Can be overridden by the -v flag.
	# Options: "quiet", "normal", "verbose"
	LogLevel = "normal"

	# Manifest (do not edit)
	CONFIG_VERSION = "1.0.0"
